apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: metrics-api

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kepler'
        static_configs:
          - targets: ['localhost:9103']
