apiVersion: v1
kind: Service
metadata:
  name: metrics-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: metrics-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
